language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - memcached

install:
  - pip install -U -r requirements/pypi.txt
  - pip install -U -r requirements/test.txt

script:
  - python -m pytest --cov=.

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_script:
  - coveralls
